package com.htec.restapi;

import com.htec.model.User;
import com.htec.service.IUserService;

import javax.annotation.security.RolesAllowed;
import javax.inject.Inject;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.util.List;

/**
 * Enables interaction with user data, and exposes them as REST API.
 */
@Path("/users")
public class UserEndpoint {

    @Inject
    private IUserService userService;

    /**
     * Returns all users stored in database.
     * @return JSON representation of users list together with response status
     */
    @RolesAllowed("ADMIN")
    @Path("/get-users")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getUsers() {

        List<User> users = userService.findAll();

        if (!users.isEmpty()) {

            return Response.ok(users).build();
        } else {
            return Response.status(Response.Status.NOT_FOUND).build();
        }
    }

    /**
     * Returns user stored in database based on its primary key/id.
     * @param id primary key/id of user to be matched by search
     * @return JSON representation of user that is found together with response status
     */
    @RolesAllowed("ADMIN")
    @Path("/find-user/{id}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response findUser(@PathParam("id") Long id) {

        User user = userService.find(id);

        if (user.getIdUser() != null) {
            return Response.ok(user).build();
        } else {
            return Response.status(Response.Status.NOT_FOUND).build();
        }
    }

    /**
     * Save new user inside database. Primary key/id is autogenerated.
     * @param firstName name of user
     * @param lastName surname of user
     * @param username unique username of user
     * @param password password of user
     * @return confirmation status if save was successful
     */
    @RolesAllowed({"ADMIN","REGULAR"})
    @Path("/save-user")
    @POST
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public Response saveUser(@FormParam("firstname") String firstName,
                             @FormParam("lastname") String lastName,
                             @FormParam("username") String username,
                             @FormParam("password") String password) {

        User user = User.builder()
                .firstName(firstName)
                .lastName(lastName)
                .username(username)
                .password(password).build();

        boolean r = userService.save(user);

        if (r) {
            return Response.ok().status(Response.Status.CREATED).build();
        } else {
            return Response.notModified().build();
        }
    }

    /**
     * Update a user stored inside database.
     * @param firstName new name of user to be updated
     * @param lastName new surname to be updated
     * @param username new username to be updated
     * @param password new password to be updated
     * @param id id of existing user which parameters will be updated
     * @return confirmation status if update was successful
     */
    @RolesAllowed({"ADMIN","REGULAR"})
    @Path("/update-user/{id}")
    @PUT
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public Response updateUser(@FormParam("firstname") String firstName,
                               @FormParam("lastname") String lastName,
                               @FormParam("username") String username,
                               @FormParam("password") String password,
                               @PathParam("id") Long id) {

        User user = User.builder()
                .firstName(firstName)
                .lastName(lastName)
                .username(username)
                .password(password).build();

        boolean r = userService.update(user, id);

        if (r) {
            return Response.ok().status(Response.Status.NO_CONTENT).build();
        } else {
            return Response.notModified().build();
        }
    }

    /**
     * Delete a user stored in database based on primary key/id.
     * @param id primary key/id of user to be deleted.
     * @return confirmation status if deletion was successful
     */
    @RolesAllowed("ADMIN")
    @Path("/delete-user/{id}")
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    public Response deleteUser(@PathParam("id") Long id) {

        boolean r = userService.delete(id);

        if (r) {
            return Response.ok().status(Response.Status.NO_CONTENT).build();
        } else {
            return Response.notModified().build();
        }
    }

    /**
     * Provides update of user role.
     * @param role new role of user to be updated by administrator.
     * @param id id of user which will have updated role
     * @return confirmation status if update was successful
     */
    @RolesAllowed("ADMIN")
    @Path("/set-role/{id}")
    @PUT
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.APPLICATION_JSON)
    public Response updateRole(@FormParam("role") String role,
                               @PathParam("id") Long id) {

        boolean r = userService.updateRole(role, id);

        if (r) {
            return Response.ok().status(Response.Status.NO_CONTENT).build();
        } else {
            return Response.notModified().build();
        }
    }

    /**
     * Provides confirmation of registration status after user created initial account with data.
     * @param id id of user which will have updated registration status in order to gain access to system
     * @return confirmation status if update was successful
     */
    @RolesAllowed("ADMIN")
    @Path("/register/{id}")
    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    public Response register(@PathParam("id") Long id) {

        boolean r = userService.register(id);

        if (r) {
            return Response.ok().status(Response.Status.NO_CONTENT).build();
        } else {
            return Response.notModified().build();
        }
    }
}